# Generated by Django 4.1 on 2022-08-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('UP', 'UP'), ('MP', 'MP'), ('Delhi', 'Delhi')], max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='pimages')),
                ('resume_doc', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
